export const PLAYERS = [
  {
    nome: "Neymar Jr.",
    idade: 34,
    numero: 10,
    posicao: "Atacante",
    clube: "Santos FC",
    altura: "1,75m",
    pe: "Direito",
    jogos: 128,
    gols: 79,
    image: "/neymar.svg",
  },
  {
    nome: "Vinícius Júnior",
    idade: 25,
    numero: 7,
    posicao: "Ponta",
    clube: "Real Madrid",
    altura: "1,76m",
    pe: "Direito",
    jogos: 38,
    gols: 7,
    image: "/vinijunior.svg",
  },
  {
    nome: "Alisson",
    idade: 33,
    numero: 1,
    posicao: "Goleiro",
    clube: "Liverpool",
    altura: "1,93m",
    pe: "Direito",
    jogos: 68,
    gols: 0,
    image: "/alisson.svg",
  },
  {
    nome: "Bruno Guimarães",
    idade: 28,
    numero: 16,
    posicao: "Volante",
    clube: "Newcastle",
    altura: "1,82m",
    pe: "Direito",
    jogos: 22,
    gols: 1,
    image: "/brunoguimaraes.svg",
  },
  {
    nome: "Casemiro",
    idade: 34,
    numero: 5,
    posicao: "Volante",
    clube: "Manchester United",
    altura: "1,85m",
    pe: "Direito",
    jogos: 75,
    gols: 7,
    image: "/casemiro.svg",
  },
  {
    nome: "Gabriel Magalhães",
    idade: 26,
    numero: 14,
    posicao: "Zagueiro",
    clube: "Arsenal",
    altura: "1,90m",
    pe: "Esquerdo",
    jogos: 12,
    gols: 1,
    image: "/gabrielmagalhaes.svg",
  },
  {
    nome: "Léo Pereira",
    idade: 28,
    numero: 15,
    posicao: "Zagueiro",
    clube: "Flamengo",
    altura: "1,88m",
    pe: "Esquerdo",
    jogos: 8,
    gols: 0,
    image: "/leopereira.svg",
  },
  {
    nome: "Marquinhos",
    idade: 32,
    numero: 4,
    posicao: "Zagueiro",
    clube: "Paris Saint-Germain",
    altura: "1,83m",
    pe: "Direito",
    jogos: 82,
    gols: 7,
    image: "/marquinhos.svg",
  },
  {
    nome: "Lucas Paquetá",
    idade: 28,
    numero: 8,
    posicao: "Meia-atacante",
    clube: "West Ham",
    altura: "1,80m",
    pe: "Esquerdo",
    jogos: 52,
    gols: 12,
    image: "/lucaspaqueta.svg",
  },
  {
    nome: "Gabriel Martinelli",
    idade: 25,
    numero: 26,
    posicao: "Atacante",
    clube: "Arsenal",
    altura: "1,78m",
    pe: "Esquerdo",
    jogos: 16,
    gols: 2,
    image: "/martinelli.svg",
  },
  {
    nome: "Raphinha",
    idade: 29,
    numero: 19,
    posicao: "Ponta",
    clube: "FC Barcelona",
    altura: "1,76m",
    pe: "Esquerdo",
    jogos: 30,
    gols: 11,
    image: "/raphinha.svg",
  },
  {
    nome: "Endrick",
    idade: 20,
    numero: 16,
    posicao: "Atacante",
    clube: "Real Madrid",
    altura: "1,73m",
    pe: "Esquerdo",
    jogos: 14,
    gols: 4,
    image: "/endrick.svg",
  },
  {
    nome: "Matheus Cunha",
    idade: 26,
    numero: 12,
    posicao: "Atacante",
    clube: "Wolverhampton",
    altura: "1,84m",
    pe: "Direito",
    jogos: 18,
    gols: 3,
    image: "/matheuscunha.svg",
  },
];